/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 40975698c76cda1ab2d3520e59dff5fd)
interface __BaseEnv_Env {
	TWIKOO_RATE_LIMITER: RateLimit;
	UPSTREAM_ORIGIN: "https://twikoo.mmtoolkit.app" | "";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface StagingEnv {
		TWIKOO_RATE_LIMITER: RateLimit;
		UPSTREAM_ORIGIN: "https://twikoo.mmtoolkit.app";
	}
	interface ProductionEnv {
		TWIKOO_RATE_LIMITER: RateLimit;
		UPSTREAM_ORIGIN: "";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "UPSTREAM_ORIGIN">> {}
}
